// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-vd2NidyWlLz0yrJ7-pZA8_50RXJ2Ik',
    appId: '1:31618739184:web:8aca2a43d15ff91c640b35',
    messagingSenderId: '31618739184',
    projectId: 'fishfeeder-638f5',
    authDomain: 'fishfeeder-638f5.firebaseapp.com',
    storageBucket: 'fishfeeder-638f5.appspot.com',
    measurementId: 'G-JNGTFDS6W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATt5sjT3-Vp4ZW8Sd0F4_DxkhSF6XXze0',
    appId: '1:31618739184:android:bc9d3cb682c33096640b35',
    messagingSenderId: '31618739184',
    projectId: 'fishfeeder-638f5',
    storageBucket: 'fishfeeder-638f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRMqIP0H6DHRrsZBhMwQOhpwa_H3LrOY',
    appId: '1:31618739184:ios:cb2e3b3455b3003b640b35',
    messagingSenderId: '31618739184',
    projectId: 'fishfeeder-638f5',
    storageBucket: 'fishfeeder-638f5.appspot.com',
    iosBundleId: 'pucminas.br.fishfeeder.trabalhoLddm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIRMqIP0H6DHRrsZBhMwQOhpwa_H3LrOY',
    appId: '1:31618739184:ios:cb2e3b3455b3003b640b35',
    messagingSenderId: '31618739184',
    projectId: 'fishfeeder-638f5',
    storageBucket: 'fishfeeder-638f5.appspot.com',
    iosBundleId: 'pucminas.br.fishfeeder.trabalhoLddm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-vd2NidyWlLz0yrJ7-pZA8_50RXJ2Ik',
    appId: '1:31618739184:web:78471fd11bea3be6640b35',
    messagingSenderId: '31618739184',
    projectId: 'fishfeeder-638f5',
    authDomain: 'fishfeeder-638f5.firebaseapp.com',
    storageBucket: 'fishfeeder-638f5.appspot.com',
    measurementId: 'G-N2J0180ENY',
  );
}
